[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[napari_sc3d_viewer.optional-dependencies]
pyvista = ["pyvista"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79